//@version=5 
strategy("Doji Strategy W with PineConnector", overlay=true, calc_on_every_tick=true, pyramiding=0,default_qty_type=strategy.percent_of_equity,default_qty_value=100,currency=currency.USD)

// **** PineConnector License ID Input ****
LicenseID = input.string(title="PineConnector License ID", defval="YourLicenseID")

//INPUTS
//MinDistance=input(100,'Minimum distance in ticks')
Use_SL_TP=input(true,'Use stop loss and take profit?')
TP=input(200,'Take Profit in ticks')
SL=input(200,'Stop Loss in tiks')
Doji = input(0.05, minval=0.01, title="Doji size", step=0.01)
LongCandleRatio = input (0.7,'Long candle ratio', step=0.1, maxval=1)
UseVolumeFilter = input(false,'Use Volume as filter (reccomended on lower TFs)')
VolumeMA=input(24,'Moving Average of Volume e.g. TF 1h - MA suggested is 24',step=1)

//VARIABILI
body=close-open
range=high-low
abody=abs(body)
ratio=abody/range
longcandle= (ratio>LongCandleRatio)

//Doji
data=(abs(open - close) <= (high - low) * Doji)
plotchar(data, title="Doji", text='Doji', color=black)
longDist= longcandle[1] and range[1]>range? high: max(high,high[1])
shortDist= longcandle[1] and range[1]>range? low: min(low,low[1])
dojilow=data==1?low:na
dojihigh=data==1?high:na

goStar=data==1? UseVolumeFilter==false? true: volume>ema(volume,VolumeMA)?true:false:false
//////////////////////////////////////////////////////////////////

//STRATEGY **** Modified for PineConnector Alerting ****
if (goStar)
    alert(str.tostring(LicenseID) + ",buy,limit=" + str.tostring(longDist),  alert.freq_once_per_bar) 
    alert(str.tostring(LicenseID) + ",sell,limit=" + str.tostring(shortDist),  alert.freq_once_per_bar) 

// Exit conditions are unchanged in this version:
strategy.exit("exit buy","buy stop",loss=SL, profit=TP, when=Use_SL_TP)
strategy.exit("exit sell","sell stop",loss=SL,profit=TP, when=Use_SL_TP)
strategy.close("buy stop",when=not Use_SL_TP and close<dojilow)
strategy.exit("exit buy","buy stop",profit=TP, when=not Use_SL_TP)
strategy.close("sell stop",when=not Use_SL_TP and close>dojihigh)
strategy.exit("exit sell","sell stop",profit=TP, when=not Use_SL_TP)